package codegen

import (
	"strings"
	"testing"
)

// The build inputs, pinned.
//
// A `Game Dev` binary needs modules, and teaching the build path to write a
// go.mod with requirements in it is the change most likely to change every
// *other* build by accident. Everything this repository publishes about
// compiled programs — the reproducibility claim in docs/compiler.md, the
// numbers in bench/, "depends only on the standard library" in the README —
// is a statement about those inputs. So they are asserted here literally,
// byte for byte, rather than described.

// stdlibProgram is what an ordinary answer-a-puzzle program's imports look
// like: a couple of standard-library packages and nothing else.
const stdlibProgram = `// Code generated by "domain build". DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"strings"
)

func main() { fmt.Fprintln(os.Stdout, strings.TrimSpace("ok")) }
`

func TestStdlibBuildInputsAreUnchanged(t *testing.T) {
	gomod, gosum, err := moduleFiles(stdlibProgram)
	if err != nil {
		t.Fatal(err)
	}
	if want := "module domainprog\n\ngo 1.22\n"; gomod != want {
		t.Errorf("go.mod for a stdlib-only program changed.\n got %q\nwant %q\n"+
			"Every published claim about compiled programs is a claim about this file.", gomod, want)
	}
	if gosum != "" {
		t.Errorf("a stdlib-only program was given a go.sum:\n%s", gosum)
	}
	args := buildArgs("/tmp/out", BuildConfig{})
	want := []string{"build", "-trimpath", "-ldflags", "-s -w", "-o", "/tmp/out", "."}
	if strings.Join(args, "\x00") != strings.Join(want, "\x00") {
		t.Errorf("build arguments changed.\n got %v\nwant %v", args, want)
	}
	env := buildEnv(false, BuildConfig{})
	if len(env) != 1 || env[0] != "CGO_ENABLED=0" {
		t.Errorf("build environment for a stdlib-only program changed.\n got %v\nwant [CGO_ENABLED=0]", env)
	}
}

// TestModuleBuildInputs is the other half: a program that names a module gets
// requirements, hashes, and the flag that lets the toolchain settle them.
func TestModuleBuildInputs(t *testing.T) {
	src := `package main

import (
	"fmt"

	tea "charm.land/bubbletea/v2"
)

func main() { fmt.Println(tea.Quit) }
`
	gomod, gosum, err := moduleFiles(src)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(gomod, "module domainprog") {
		t.Errorf("go.mod has no module line:\n%s", gomod)
	}
	if !strings.Contains(gomod, "go "+depsGoVersion) {
		t.Errorf("go.mod does not declare the repository's language version:\n%s", gomod)
	}
	if !strings.Contains(gomod, "\tcharm.land/bubbletea/v2 v") {
		t.Errorf("go.mod does not require Bubble Tea:\n%s", gomod)
	}
	if !strings.Contains(gosum, "charm.land/bubbletea/v2 v") {
		t.Error("go.sum has no hash for Bubble Tea, so the build could not verify it")
	}
	env := buildEnv(true, BuildConfig{})
	if len(env) != 2 || env[1] != "GOFLAGS=-mod=mod" {
		t.Errorf("a module build needs -mod=mod, got %v", env)
	}
}

// TestUnknownModuleIsRefused: an emitter that grows an import the repository
// does not depend on fails here rather than sending `go build` to the network.
func TestUnknownModuleIsRefused(t *testing.T) {
	src := `package main

import _ "example.com/nothing/at/all"

func main() {}
`
	if _, _, err := moduleFiles(src); err == nil {
		t.Fatal("expected an import no requirement covers to be refused")
	} else if !strings.Contains(err.Error(), "example.com/nothing/at/all") {
		t.Errorf("the error should name the import, got: %v", err)
	}
}

func TestExternalImportsIgnoresTheStandardLibrary(t *testing.T) {
	src := `package main

import (
	"fmt"
	_ "net/http"
	"runtime/debug"

	"github.com/charmbracelet/x/term"
)

func main() { fmt.Println(debug.GCStats{}, term.IsTerminal(0)) }
`
	got, err := externalImports(src)
	if err != nil {
		t.Fatal(err)
	}
	if len(got) != 1 || got[0] != "github.com/charmbracelet/x/term" {
		t.Errorf("got %v, want just the one external import", got)
	}
}

// TestModuleHeaderOnlyWhenNeeded: `--emit-go` writes exactly what it always
// wrote for a program that depends only on the standard library, and adds the
// module file — after the generated-by line, which stays first — for one that
// does not.
func TestModuleHeaderOnlyWhenNeeded(t *testing.T) {
	got, err := WithModuleHeader(stdlibProgram)
	if err != nil {
		t.Fatal(err)
	}
	if got != stdlibProgram {
		t.Error("a stdlib-only program's emitted source gained a header it does not need")
	}

	src := "// Code generated by \"domain build\". DO NOT EDIT.\n\npackage main\n\n" +
		"import (\n\t\"fmt\"\n\n\ttea \"charm.land/bubbletea/v2\"\n)\n\nfunc main() { fmt.Println(tea.Quit) }\n"
	got, err = WithModuleHeader(src)
	if err != nil {
		t.Fatal(err)
	}
	first, rest, _ := strings.Cut(got, "\n")
	if first != `// Code generated by "domain build". DO NOT EDIT.` {
		t.Errorf("the generated-by line should stay first, got %q", first)
	}
	for _, want := range []string{"//\tmodule domainprog", "//\tgo " + depsGoVersion, "//\t\tcharm.land/bubbletea/v2 v"} {
		if !strings.Contains(rest, want) {
			t.Errorf("the header should contain %q:\n%s", want, rest)
		}
	}
	if !strings.Contains(rest, "package main") {
		t.Error("the header replaced the program instead of prefixing it")
	}
}
